# Generated by Django 5.1.4 on 2025-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tin_number',
        ),
        migrations.AddField(
            model_name='business',
            name='tin_number',
            field=models.CharField(default='000000000', max_length=20, unique=True, verbose_name='TIN Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Phone Number'),
        ),
    ]
